services:
  nginx:
    build: ./client
    ports:
      - "8090:8080"
    volumes:
      - client_target:/var/www/spotilisk

  build:
    build:
      context: ./client
      target: build
    volumes:
      - ./client:/usr/src/app
      - client_target:/usr/src/app/target
      - client_node_modules:/usr/src/app/node_modules
    command: node --run debug

volumes:
  client_node_modules:
  client_target:
