services:
  nginx:
    build: ./client
    ports:
      - "8090:8080"
    volumes:
      - ./client/src:/var/www/spotilisk

  # app:
  #   build: ./server
  #   volumes:
  #     - ./server:/usr/src/app
  #     - node_modules:/usr/src/app/node_modules
  #   ports:
  #     - "9229:9229"
  #   command: npm run debug

# volumes:
#   node_modules:
